# Title     : Script to refine guess labels
# Objective : To apply a few steps to refine 
#             the guess labels generated by random forest.
# Created by: Lei Song
# Created on: 03/23/21

#######################
##  Step 1: Setting  ##
#######################
message('Step1: Setting')

library(glue)
library(here)
library(terra)
library(ramify)
library(sf)
library(rgrass7)
library(dplyr)
library(tidyverse)
library(parellel)

###############################
###  Step 2: Refine labels  ###
###############################
message('Step 2: Refine labels')

# Define function to refine the labels
## Step 0: Remove predicted buildings.
## Step 1: Apply zonal mode to objects that are over segmented.
## Step 2: Add roads, waterbodies, and buildings. (No rivers)
## Step 3: Split a whole tile into 512 * 512 (or 256 * 256).
refine_label <- function(tile_id, src_dir, img_dir, tiles){
    # tile_id <- '1208-996'
    # src_dir <- here('results/north/prediction')
    # img_dir <- here('data/plts_nicfi')
    # tiles <- st_read('data/geoms/tiles_nicfi_north.geojson')
    # roads <- st_read(here('data/osm/big_roads.geojson'))
    # waterbodies <- st_read(here('data/osm/waterbodies.geojson'))
    # buildings <- st_read(here('data/osm/buildings.geojson'))
    # Read images
    scores <- rast(file.path(src_dir, glue('scores_{tile_id}.tif')))
    
    # Remove predicted buildings
    classes_path <- file.path(tempdir(), 'temp.tif')
    scores <- subset(scores, c(1:5, 7))
    pred <- argmax(values(scores))
    classes <- scores[[1]]
    values(classes) <- pred
    writeRaster(classes, classes_path,
                wopt = list(datatype = 'INT1U',
                            gdal=c("COMPRESS=LZW")),
                overwrite = T)
    rm(scores, pred, classes); rm()
    # So here:
    # 1: cropland
    # 2: forest
    # 3: grassland
    # 4: shrubland
    # 5: water
    # 6: bareland
    
    # Do segmentation
    nicfi_prefix <- 'planet_medres_normalized_analytic'
    s1_prefix <- '2017-12_2018-05'
    s2_prefix <- '2018-06_2018-11'
    seg_path <- tempfile()
    gisBase <- '/Applications/GRASS-7.8.app/Contents/Resources'
    initGRASS(gisBase = gisBase,
              home = tempdir(),
              gisDbase = tempdir(),  
              mapset = 'PERMANENT', 
              location = 'segments', 
              override = TRUE)
    execGRASS("g.proj", flags = "c", 
              proj4 = crs(rast(
                  file.path(
                      img_dir,
                      glue('{nicfi_prefix}_{s1_prefix}_mosaic_{tile_id}.tif'))),
                  proj4 = T))
    execGRASS('r.in.gdal', flags = c("o", "overwrite"),
              input = file.path(
                  img_dir,
                  glue('{nicfi_prefix}_{s1_prefix}_mosaic_{tile_id}.tif')),
              band = 1:4,
              output = "s1")
    execGRASS('r.in.gdal', flags = c("o", "overwrite"),
              input = file.path(
                  img_dir,
                  glue('{nicfi_prefix}_{s2_prefix}_mosaic_{tile_id}.tif')),
              band = 1:4,
              output = "s2")
    execGRASS("g.region", raster = "s1.blue")
    execGRASS("i.group", group = 's1_s2',
              input = c('s1.blue', 's1.green', 's1.red', 's1.4',
                        's2.blue', 's2.green', 's2.red', 's2.4'))
    execGRASS("i.segment", flags = c("overwrite"),
              parameters = list(
                  group = 's1_s2',
                  threshold = 0.2,
                  method = "mean_shift",
                  similarity = "manhattan",
                  minsize = 50,
                  memory = 1024 * 16,
                  iterations = 200,
                  output = 'segments',
                  goodness = 'goodness'))
    execGRASS('r.in.gdal', flags = c("o", "overwrite"),
              input = classes_path,
              band = 1,
              output = "classes")
    execGRASS('r.statistics', flags = c('c', "overwrite"),
              base = 'segments',
              cover = 'classes',
              method = 'mode',
              output = "classes_mode")
    execGRASS('r.mapcalc', expression = "classes_new = @classes_mode")
    execGRASS('r.out.gdal', flags = c("m", "overwrite"),
              output = seg_path,
              input = "classes_new")
    
    # Apply zonal mode to objects
    classes <- rast(seg_path)
    file.remove(classes_path)
    
    # Add roads, waterbodies, and buildings
    tile <- tiles %>% filter(tile == tile_id) %>% 
        st_buffer(0.01)
    crs_mer <- crs(rast(
        file.path(
            img_dir,
            glue('{nicfi_prefix}_{s1_prefix}_mosaic_{tile_id}.tif'))),
        proj4 = T)
    road <- roads %>% 
        st_intersection(tile) %>% 
        st_cast('MULTILINESTRING') %>% 
        st_transform(crs = crs_mer)
    waterbody <- waterbodies %>% 
        st_intersection(tile) %>% 
        st_cast('MULTIPOLYGON') %>% 
        st_transform(crs = crs_mer)
    building <- buildings %>% 
        st_intersection(tile) %>% 
        st_cast('MULTIPOLYGON') %>% 
        st_transform(crs = crs_mer)
    
    use_sf()
    if (nrow(road) > 0){
        writeVECT(road, 'roads', v.in.ogr_flags = 'overwrite')
        execGRASS('v.to.rast', flags = c("overwrite"),
                  parameters = list(input = 'roads', 
                                    output = 'roads',
                                    use = 'val',
                                    value = 6))
        roads_path <- tempfile()
        execGRASS('r.out.gdal', flags = c("m", "overwrite"),
                  output = roads_path,
                  input = "roads")
        fill_roads <- rast(roads_path)
    } else {
        fill_roads <- NULL
    }
    
    if (nrow(waterbody) > 0){
        writeVECT(waterbody, 'waterbodies', v.in.ogr_flags = 'overwrite')
        execGRASS('v.to.rast', flags = c("overwrite"),
                  parameters = list(input = 'waterbodies', 
                                    output = 'waterbodies',
                                    use = 'val',
                                    value = 5))
        waterbody_path <- tempfile()
        execGRASS('r.out.gdal', flags = c("m", "overwrite"),
                  output = waterbody_path,
                  input = "waterbodies")
        fill_waterbodies <- rast(waterbody_path)
    } else {
        fill_waterbodies <- NULL
    }
    
    if (nrow(building) > 0){
        writeVECT(building, 'buildings', v.in.ogr_flags = 'overwrite')
        execGRASS('v.to.rast', flags = c("overwrite"),
                  parameters = list(input = 'buildings', 
                                    output = 'buildings',
                                    use = 'val',
                                    value = 7))
        building_path <- tempfile()
        execGRASS('r.out.gdal', flags = c("m", "overwrite"),
                  output = building_path,
                  input = "buildings")
        fill_buildings <- rast(building_path)
    } else {
        fill_buildings <- NULL
    }
    
    fills <- compact(list(roads = fill_roads, 
                          waterbodies = fill_waterbodies, 
                          buildings = fill_buildings))
    rm(fill_roads, fill_buildings, fill_waterbodies)
    
    # Replace values
    for (i in 1:length(fills)){
        mask <- fills[[i]]
        mask <- is.na(mask)
        classes <- classes * mask
        classes <- cover(classes, fills[[i]], values = 0)
    }
    
    # Split into sub-tiles
    message('------Split to tiles')
    tiles_layout <- aggregate(classes, fact = size_sub_tile)
    values(tiles_layout) <- 1:(4096 / size_sub_tile)^2
    
    invisible(mclapply(values(tiles_layout), function(index){
        tile <- tiles_layout
        tile <- tile == index
        tile[tile == 0] <- NA
        tile <- disaggregate(tile, fact = size_sub_tile)
        classes_tile <- classes * tile
        classes_tile <- terra::trim(classes_tile)
        
        # Save out
        writeRaster(classes_tile, 
                    file.path(labels_dir, 
                              glue('refine_{tile_id}_{index}.tif')),
                    wopt = list(datatype = 'INT1U',
                                gdal=c("COMPRESS=LZW")))
        rm(tile, classes_tile);gc()
    }, mc.core = 2))
}

# Refine guess labels for each time
## Prepare necessary files
message('--Prepare necessary files')

src_dir <- here('results/north/prediction')
img_dir <- here('data/plts_nicfi')
labels_dir <- here('results/north/guess_labels')
tiles <- st_read('data/geoms/tiles_nicfi_north.geojson')
roads <- st_read(here('data/osm/roads.geojson'))
roads <- roads %>%
    filter(fclass %in% c('primary', 'secondary', 'tertiary',
                         'trunk', 'primary_link', 'secondary_link',
                         'tertiary_link', 'rail'))
waterbodies <- st_read(here('data/osm/waterbodies.geojson'))
buildings <- st_read(here('data/osm/buildings.geojson'))

## Get tiles
fnames <- list.files(here(src_dir), pattern = 'classed')
tile_ids <- str_extract(fnames, '[0-9]+-[0-9]+')

lapply(tile_ids, function(tile_id) {
    message(glue('----{tile_id}'))
    refine_label(tile_id, src_dir, img_dir, 
                 labels_dir, tiles, roads, 
                 waterbodies, buildings)})
