# Title     : Script to refine guess labels
# Objective : To apply a few steps to refine 
#             the guess labels generated by random forest.
# Created by: Lei Song
# Created on: 03/23/21

####################### 
##  Step 1: Setting  ##
#######################
message('Step 1: Setting')

library(glue)
library(here)
library(terra)
library(ramify)
library(sf)
library(rgrass7)
library(dplyr)
library(stringr)
library(tidyverse)
library(parallel)

###############################
###  Step 2: Refine labels  ###
###############################
message('Step 2: Refine labels')

# Define function to refine the labels
## Step 2-0: Reduce the weight of predicted buildings.
## Step 2-1: Add roads, waterbodies, and buildings. (No rivers)
## Step 2-2: Split a whole tile into 512 * 512 (or 256 * 256).
refine_label <- function(tile_id, src_dir, 
                         labels_dir, tiles, roads, 
                         waterbodies, buildings, 
                         size_sub_tile = 512){
    message('------Modify classses')
    # Read images
    scores <- rast(file.path(src_dir, glue('scores_{tile_id}.tif')))
    
    # Reduce the weight of predicted buildings
    scores$.pred_8 <- scores$.pred_8 * 0.2
    pred <- values(scores); pred[is.na(pred)] <- 0
    pred <- argmax(pred)
    classes <- scores[[1]]
    values(classes) <- pred
    rm(scores, pred); gc()
    # So here:
    # 1: cropland
    # 2: forest
    # 3: grassland
    # 4: shrubland
    # 5: water
    # 6: Urban
    # 7: bareland
    
    # Set up GRASS GIS
    message('------Add OSM layers')
    gisBase <- '/Applications/GRASS-7.9.app/Contents/Resources'
    initGRASS(gisBase = gisBase,
              home = tempdir(),
              gisDbase = tempdir(),  
              mapset = 'PERMANENT', 
              location = 'segments', 
              override = TRUE)
    execGRASS("g.proj", flags = "c", 
              proj4 = crs(rast(
                  file.path(src_dir, glue('scores_{tile_id}.tif'))),
                  proj4 = T))
    execGRASS('r.in.gdal', flags = c("o", "overwrite"),
              input = file.path(src_dir, glue('scores_{tile_id}.tif')),
              band = 1,
              output = "score")
    execGRASS("g.region", raster = "score")

    
    # Add roads, waterbodies, and buildings
    tile <- tiles %>% filter(tile == tile_id) %>% 
        st_buffer(0.01)
    crs_mer <- crs(rast(
        file.path(src_dir, glue('scores_{tile_id}.tif'))),
        proj4 = T)
    road <- roads %>% 
        st_intersection(tile) %>% 
        st_cast('MULTILINESTRING') %>% 
        st_transform(crs = crs_mer)
    waterbody <- waterbodies %>% 
        st_intersection(tile) %>% 
        st_cast('MULTIPOLYGON') %>% 
        st_transform(crs = crs_mer)
    building <- buildings %>% 
        st_intersection(tile) %>% 
        st_cast('MULTIPOLYGON') %>% 
        st_transform(crs = crs_mer)
    
    use_sf()
    if (nrow(road) > 0){
        writeVECT(road, 'roads', v.in.ogr_flags = 'overwrite')
        execGRASS('v.to.rast', flags = c("overwrite"),
                  parameters = list(input = 'roads', 
                                    output = 'roads',
                                    use = 'val',
                                    value = 7))
        roads_path <- tempfile()
        execGRASS('r.out.gdal', flags = c("m", "overwrite"),
                  output = roads_path,
                  input = "roads")
        fill_roads <- rast(roads_path)
    } else {
        fill_roads <- NULL
    }
    
    if (nrow(waterbody) > 0){
        writeVECT(waterbody, 'waterbodies', v.in.ogr_flags = 'overwrite')
        execGRASS('v.to.rast', flags = c("overwrite"),
                  parameters = list(input = 'waterbodies', 
                                    output = 'waterbodies',
                                    use = 'val',
                                    value = 5))
        waterbody_path <- tempfile()
        execGRASS('r.out.gdal', flags = c("m", "overwrite"),
                  output = waterbody_path,
                  input = "waterbodies")
        fill_waterbodies <- rast(waterbody_path)
    } else {
        fill_waterbodies <- NULL
    }
    
    if (nrow(building) > 0){
        writeVECT(building, 'buildings', v.in.ogr_flags = 'overwrite')
        execGRASS('v.to.rast', flags = c("overwrite"),
                  parameters = list(input = 'buildings', 
                                    output = 'buildings',
                                    use = 'val',
                                    value = 6))
        building_path <- tempfile()
        execGRASS('r.out.gdal', flags = c("m", "overwrite"),
                  output = building_path,
                  input = "buildings")
        fill_buildings <- rast(building_path)
    } else {
        fill_buildings <- NULL
    }
    
    # Gather results
    fills <- compact(list(roads = fill_roads, 
                          waterbodies = fill_waterbodies, 
                          buildings = fill_buildings))
    rm(fill_roads, fill_buildings, fill_waterbodies)
    
    # Replace values
    if (length(fills) > 0){
        for (i in 1:length(fills)){
            mask <- fills[[i]]
            mask <- is.na(mask)
            classes <- classes * mask
            classes <- cover(classes, fills[[i]], values = 0)
        }
    }
    
    # Split into sub-tiles
    message('------Split to tiles')
    tiles_layout <- aggregate(classes, fact = size_sub_tile)
    values(tiles_layout) <- 1:(4096 / size_sub_tile)^2
    
    invisible(lapply(values(tiles_layout, mat = F), 
                       function(index){
        tile <- copy(tiles_layout)
        tile <- tile == index
        tile[tile == 0] <- NA
        tile <- disaggregate(tile, fact = size_sub_tile)
        classes_tile <- classes * tile
        classes_tile <- terra::trim(classes_tile)
        
        # Save out
        writeRaster(classes_tile, 
                    file.path(labels_dir, 
                              glue('refine_{tile_id}_{index}.tif')),
                    wopt = list(datatype = 'INT1U',
                                gdal=c("COMPRESS=LZW")))
        rm(tile, classes_tile); gc()
    }))
}

# Refine guess labels for each time
## Prepare necessary files
message('--Prepare necessary files')

src_dir <- here('results/north/prediction')
labels_dir <- here('results/north/guess_labels')
if (!dir.exists(labels_dir)) dir.create(labels_dir)
tiles <- st_read('data/geoms/tiles_nicfi_north.geojson',
                 quiet = T)
roads <- st_read(here('data/osm/roads.geojson'), quiet = T)
roads <- roads %>%
    filter(fclass %in% c('primary', 'secondary', 'tertiary',
                         'trunk', 'primary_link', 'secondary_link',
                         'tertiary_link', 'rail'))
waterbodies <- st_read(here('data/osm/waterbodies.geojson'),
                       quiet = T)
buildings <- st_read(here('data/osm/buildings.geojson'),
                     quiet = T)

## Get tiles
message('--Start refine labels')
fnames <- list.files(here(src_dir), pattern = 'classed')
tile_ids <- str_extract(fnames, '[0-9]+-[0-9]+')
tile_ids <- tile_ids[52:length(tile_ids)]

lapply(tile_ids, function(tile_id) {
    message(glue('----Tile id: {tile_id}'))
    refine_label(tile_id, src_dir,  
                 labels_dir, tiles, roads, 
                 waterbodies, buildings)
})
