---
title: "Some prework before model traning"
author: "Lei Song"
date: "`r Sys.Date()`"
output: 
  rmdformats::readthedown:
    highlight: pygments
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

## Introduction
Some pre-work before model training:

- Upload files to our AWS S3 bucket.
- Make the data catalog.

## Upload imagery
Upload the images and labels to AWS S3 bucket.

```{r upload}
library(aws.s3)
library(parallel)

## PlanetScope quads
plt_quads_rain_season <- list.files('/Volumes/elephant/plt_nicfi',
                        full.names = T, pattern = '2017-12_2018-05')
plt_quads_dry_season <- list.files('/Volumes/elephant/plt_nicfi',
                        full.names = T, pattern = '2018-06_2018-11')
## Labels
lc_labels <- list.files('/Volumes/elephant/labels',
                        full.names = T, pattern = '.tif$')

## Upload function
s3_upload <- function(fnames, prefix, bucket){
    mclapply(fnames, function(src_path){
    put_object(file = src_path, 
           object = file.path(prefix, 
                              basename(src_path)), 
           bucket = bucket)
}, mc.cores = 6)
}

## Upload
s3_upload(plt_quads_rain_season, 
          "tz_dl_data/planet_quads/rain", 
          'activemapper')
s3_upload(plt_quads_dry_season, 
          "tz_dl_data/planet_quads/dry", 
          'activemapper')
s3_upload(lc_labels, 
          "tz_dl_data/lc_labels", 
          'activemapper')
```

## Make catalog

```{r catalog}
library(dplyr)
library(stringr)
library(tidyr)
library(aws.s3)

# Rain season
items <- get_bucket(bucket = 'activemapper', 
                    prefix = 'tz_dl_data/planet_quads/rain', 
                    max = Inf)
keys <- lapply(c(2:length(items)), function(i) {
    basename(items[[i]]$Key)
})
plts_rain <- unlist(keys) %>% 
    paste0('s3://activemapper/tz_dl_data/planet_quads/rain/', .) %>% 
    data.frame(dir_gs = .) %>% 
    mutate(tile = str_extract(str_extract(dir_gs, 
                                          '[0-9]+-[0-9]+.tif'), 
                              '[0-9]+-[0-9]+'))

# Dry season
items <- get_bucket(bucket = 'activemapper', 
                    prefix = 'tz_dl_data/planet_quads/dry', 
                    max = Inf)
keys <- lapply(c(2:length(items)), function(i) {
    basename(items[[i]]$Key)
})
plts_dry <- unlist(keys) %>% 
    paste0('s3://activemapper/tz_dl_data/planet_quads/dry/', .) %>% 
    data.frame(dir_os = .) %>% 
    mutate(tile = str_extract(str_extract(dir_os, 
                                          '[0-9]+-[0-9]+.tif'), 
                              '[0-9]+-[0-9]+'))
plts <- merge(plts_rain, plts_dry, by = 'tile')
rm(plts_rain, plts_dry)

# Labels
items <- get_bucket(bucket = 'activemapper', 
                    prefix = 'tz_dl_data/lc_labels', 
                    max = Inf)
keys <- lapply(c(2:length(items)), function(i) {
    basename(items[[i]]$Key)
})
lc_labels <- unlist(keys) %>% 
    paste0('s3://activemapper/tz_dl_data/lc_labels/', .) %>% 
    data.frame(dir_label = .) %>% 
    mutate(name = str_extract(dir_label, 
                              '[0-9]+-[0-9]+_[0-9]+')) %>% 
    tidyr::separate(name, c('tile', 'index'), '_')
imgs <- merge(lc_labels, plts, by = 'tile')
rm(plts, lc_labels)

catalog_train_val_test <- read.csv('data/intermid/catalog_train_val_test.csv',
                                  stringsAsFactors = F) %>% 
    merge(imgs, by = c('tile', 'index')) %>% 
    mutate(name = paste(tile, index, sep = '-')) %>% 
    dplyr::select(name, usage, dir_gs, dir_os, dir_label)
write.csv(catalog_train_val_test, 'data/intermid/catalog_DL_train_val_test.csv',
          row.names = F)
put_object(file = 'data/intermid/catalog_DL_train_val_test.csv', 
           object = 'tz_dl_data/catalogs/catalog_DL_train_val_test.csv', 
           bucket = 'activemapper')
```
